server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      database: book-retailer
      port: 27017

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info

app:
  api:
    version: 1.0.0
    title: Book Service
    basePackage: com.book
    description: Book service api documentation
    swagger:
      enable: true